### ISSUE TITLE
Interested members

### ISSUE THREAD

**Issue by devkhan** [ClusterInnovationCentre/aphrodite#1]
Interested members may reply on this thread. Even though, only two will be responsible for the project, everyone can still contribute(by opening an issue/pull request).

**Comment by prashnts** [comment]
The technology stack is the following, no prerequisite required, except that the members involved should be open to explore new frameworks/ideas.
- SASS, Bourbon and Bitters
- Coffeescript

Additionally, we may use the following JS framework/libraries:
- MomentJS
- JQuery
- Vex
- Masonry

**Comment by vivekpatle** [comment]
I am interested in this project. :)

**Comment by kumarvivek9097** [comment]
im intrested in this project. i have good knowledge of html and css.

**Comment by sagar15795** [comment]
i am also interested  in this.

**Comment by pa1pal** [comment]
I'm interested in this.
