### ISSUE TITLE
GitHub Pages not able to build.

### ISSUE THREAD

**Issue by devkhan** [ClusterInnovationCentre/aphrodite#3]
gh-pages is not able to build the site as it tries to build it from the root directory, whereas it should be done from `ducic`. Need to fix this.

**Comment by prashnts** [comment]
Since we didn't intend to use github pages, I didn't add it to the root directory. Do we want that?

**Comment by devkhan** [comment]
Not really, but wouldn't that be good for debugging purposes? 

I mean, we can't experiment with the production website. And btw, I tried setting `source` in jekyll config, but its not working for me, can someone take a look please?

**Comment by prashnts** [comment]
Closed in 1fbe7f339b0200bd27eb4f2ec9b5d7b71e8e6b99
